### PR TITLE
Ensure Material for iOS is below Scaffold

### LINKED ISSUE #284: PlatformIconButton on PlatformAppBar placed too low on iOS
PlatformIconButton on PlatformAppBar is placed too low on iOS it seem. If i change it to a IconButton, it seem correct (but does not work on iOS in some cases).

Example:

```
class MenuPage extends StatelessWidget {
  MenuPage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return PlatformScaffold(
      appBar: PlatformAppBar(
        leading: PlatformIconButton(
          icon: Icon(PlatformIcons(context).clear),
          onPressed: () {
            Navigator.of(context).pop();
          },
        ),
      ),
      body: SafeArea(
        child: MenuContent(),
      ),
    );
  }
}
```

### PR DESCRIPTION
**Pull request by aqwert**
fixes #284 and #287

### CODE REVIEW

**Comment by erf** [comment]
I tried to run my example from #284 using this branch, but it crashed with the following exception:

```
═╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown building IconButton(Icon, padding: EdgeInsets.all(8.0), dirty):
No Material widget found.
IconButton widgets require a Material widget ancestor.
In material design, most widgets are conceptually "printed" on a sheet of material. In Flutter's
material library, that material is represented by the Material widget. It is the Material widget
that renders ink splashes, for instance. Because of this, many material library widgets require that
there be a Material widget in the tree above them.
To introduce a Material widget, you can either directly include one, or use a widget that contains
Material itself, such as a Card, Dialog, Drawer, or Scaffold.
The specific widget that could not find a Material ancestor was:
  IconButton
The ancestors of this widget were:
  ...
  Row
  IconTheme
  Builder
  Padding
  KeyedSubtree-[GlobalKey#03606 Trailing]
  ...

The relevant error-causing widget was:
  IconButton file:///Users/erlend/projects/platform_test/lib/main.dart:63:11
When the exception was thrown, this was the stack:
#0      debugCheckHasMaterial.<anonymous closure> (package:flutter/src/material/debug.dart:27:7)
#1      debugCheckHasMaterial (package:flutter/src/material/debug.dart:48:4)
#2      IconButton.build (package:flutter/src/material/icon_button.dart:330:12)
#3      StatelessElement.build (package:flutter/src/widgets/framework.dart:4673:28)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4599:15)
#5      Element.rebuild (package:flutter/src/widgets/framework.dart:4289:5)
#6      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4577:5)
#7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4572:5)
#8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3629:14)
#9      MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6251:36)
#10     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6262:32)
...     Normal element mounting (28 frames)
#38     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3629:14)
#39     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6251:36)
#40     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6262:32)
...     Normal element mounting (69 frames)
#109    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3629:14)
#110    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6251:36)
#111    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6262:32)
...     Normal element mounting (197 frames)
#308    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3629:14)
#309    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6251:36)
#310    Element.updateChild (package:flutter/src/widgets/framework.dart:3381:18)
#311    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5683:32)
#312    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6273:17)
#313    Element.updateChild (package:flutter/src/widgets/framework.dart:3368:15)
#314    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4624:16)
#315    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4772:11)
#316    Element.rebuild (package:flutter/src/widgets/framework.dart:4289:5)
#317    StatefulElement.update (package:flutter/src/widgets/framework.dart:4804:5)
#318    Element.updateChild (package:flutter/src/widgets/framework.dart:3368:15)
#319    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4624:16)
#320    Element.rebuild (package:flutter/src/widgets/framework.dart:4289:5)
#321    ProxyElement.update (package:flutter/src/widgets/framework.dart:4951:5)
#322    Element.updateChild (package:flutter/src/widgets/framework.dart:3368:15)
#323    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4624:16)
#324    Element.rebuild (package:flutter/src/widgets/framework.dart:4289:5)
#325    ProxyElement.update (package:flutter/src/widgets/framework.dart:4951:5)
#326    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:181:11)
#327    Element.updateChild (package:flutter/src/widgets/framework.dart:3368:15)
#328    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6120:14)
#329    Element.updateChild (package:flutter/src/widgets/framework.dart:3368:15)
#330    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4624:16)
#331    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4772:11)
#332    Element.rebuild (package:flutter/src/widgets/framework.dart:4289:5)
#333    StatefulElement.update (package:flutter/src/widgets/framework.dart:4804:5)
#334    Element.updateChild (package:flutter/src/widgets/framework.dart:3368:15)
#335    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6120:14)
#336    Element.updateChild (package:flutter/src/widgets/framework.dart:3368:15)
#337    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6120:14)
#338    Element.updateChild (package:flutter/src/widgets/framework.dart:3368:15)
#339    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4624:16)
#340    Element.rebuild (package:flutter/src/widgets/framework.dart:4289:5)
#341    ProxyElement.update (package:flutter/src/widgets/framework.dart:4951:5)
#342    Element.updateChild (package:flutter/src/widgets/framework.dart:3368:15)
#343    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4624:16)
#344    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4772:11)
#345    Element.rebuild (package:flutter/src/widgets/framework.dart:4289:5)
#346    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2583:33)
#347    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:878:21)
#348    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:328:5)
#349    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1150:15)
#350    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1087:9)
#351    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1003:5)
#355    _invoke (dart:ui/hooks.dart:163:10)
#356    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:259:5)
#357    _drawFrame (dart:ui/hooks.dart:126:31)
(elided 3 frames from dart:async)
```

My pubspec.yaml:

```
  flutter_platform_widgets:
    git: 
      url: https://github.com/stryder-dev/flutter_platform_widgets
      ref: fix-#284-#287-Material-with-iOS
```

**Comment by aqwert** [comment]
I will have a look.

**Comment by aqwert** [comment]
@erf It should now be resolved if you want to have a look again

**Comment by erf** [comment]
The last commit solved it! Thank you so much!

**Pull request merged**
