### PR TITLE
Add remove icon and icon func to return custom platform icon (beta null safety)

### PR DESCRIPTION
**Pull request by vincevargadev**
See commit messages and their links to the opened issues.

### CODE REVIEW

**Comment by aqwert** [comment]
I can merge this is. Can you can you change the PR to be based of master as that is now the main null safe branch

**Comment by vincevargadev** [comment]
@aqwert I changed the branch to master. Would it work for you like this?

**Comment by aqwert** [comment]
You will need to pull from master and then rebase to HEAD so that it does not pick up commits already there

**Comment by vincevargadev** [comment]
Ok, I'll try to do it in the next days

**Comment by aqwert** [comment]
Instead of fixing this PR, I will just take the contents and create another

**Pull request closed without merging**
