### PR TITLE
Update example environment version, Add PlatformCheckbox, PlatformRadio, PlatformDropdownButton

### PR DESCRIPTION
**Pull request by bookshiyi**
Thanks

### CODE REVIEW

**Comment by bookshiyi** [comment]
Although Flutter natively provides the API for checkbox.adaptive and radio.adaptive to achieve automatic style conversion of widgets on different platforms, in order to maintain the code consistency of flutter_platform_widget, I still submitted this pull request.

**Comment by aqwert** [comment]
Yes. probably a good idea. Also there are now `SwitchListTile.adaptive`, `RadioListTile.adaptive` and `CheckboxListTile.adaptive`

**Review by aqwert — CHANGES_REQUESTED** [review]
Can you separate the 3 platform widgets into separate PRs. Thanks

**Comment by bookshiyi** [comment]
I have separated into three PRs  #417 #418 #419 . Thanks.

**Pull request closed without merging**
