### PR TITLE
Added PlatformSelect

### PR DESCRIPTION
**Pull request by kasp1**
Hi, this one was a bit challenging for me as I am very new to both Dart and Flutter. Hope the code is rather consistent with yours.

### CODE REVIEW

**Comment by aqwert** [comment]
Thanks. I will need to find time to review this but it does look quite well put together. There are special considerations around required parameters and parameters with default values that I will need to check

**Comment by kasp1** [comment]
Added PlatformListView, which I needed. Check it out and let me know what do you think (scroll for images): https://github.com/kasp1/flutter_platform_widgets/blob/master/README.md#platformlistview

**Comment by mlandry-devolutions** [comment]
Any plan to merge this for next version ?
Thanks!

**Comment by aqwert** [comment]
I won't be merging all of this code as it contains a PlatformListView which is not based off a cupertino widget but rather than a more opinionated implementation. I will be having time soon to look at a PlatformSelect implementation

**Comment by aqwert** [comment]
I am closing this PR as it will not get merged in the current state as it is too opinionated as to the implementation. I have a ticket for #148 and #66 that will be used to track improvements

**Pull request closed without merging**
